### ISSUE TITLE
Validation for required fields doesn't work (Seems like no Validation is working)

### ISSUE THREAD

**Issue by SteveGZr** [jaimegildesagredo/booby#30]
The validation for 'required=True' on fields doesn't work for me, I tried to use it on a String, but after I applied it, I can still create a Model with empty fields and even set the fields to None.

**Comment by SteveGZr** [comment]
I have something like this:
     
     from booby.fields import String, Integer
     from booby.models import Model
     
     class ExampleModel(Model):
         id = Integer()
         some_string = String(required=True)

And when I now create a instance like in one of the following lines, it doesn't give me an error or something:

    example = ExampleModel(id=1, some_string=None)
    example = ExampleModel()

**Comment by SteveGZr** [comment]
Seems like no validation is working, just tested it.
I'm getting no ValidationError if I have something like:

    class ExampleModel(Model):
        id = Integer()
        some_string = String()
        some_float = Float()
        some_bool = Boolean()

And then do something like:

    example = ExampleModel(id='foo', some_string=1337, some_float=True, some_bool=42.4711)

**Comment by jaimegildesagredo** [comment]
Hi @SteveGZr and thank you for your issue.

I think the problem here is that you're expecting booby to perform the validation on model initialization, but booby doesn't do so.

Instead you need to call any of the validation methods: [is_valid](http://booby.readthedocs.org/en/v0.7.0/models.html#models.Model.is_valid) or [validate](http://booby.readthedocs.org/en/v0.7.0/models.html#models.Model.validate) after your model instance is filled.

I think this will solve the problem. Let me know if you need anything else.
